#pragma once

const char *blud_boot = 
"-- Make sure love table exists.\n"
"if not blud then blud = {} end\n"
"-- Used for setup:\n"
"blud.path = {}\n"
"blud.arg = {}\n"
"blud.mouse = {}\n"
"blud.key = {}\n"
"-- Unparsed arguments:\n"
"argv = {}\n"
"function blud.update(dt)\n"
"	-- do nothing when initially launching\n"
"end\n"
"function blud.draw()\n"
"	-- do nothing when initially launching\n"
"end\n"
"function blud.key.pressed(key)\n"
"	print(\"key pressed\")\n"
"	-- do nothing when initially launching\n"
"end\n"
"function blud.key.released(key)\n"
"	print(\"key released\")\n"
"	-- do nothing when initially launching\n"
"end\n"
"function blud.mouse.moved(x, y)\n"
"	print(\"mouse moved\")\n"
"	-- do nothing when initially launching\n"
"end\n"
"function blud.mouse.dragged(x, y, button)\n"
"	print(\"mouse dragged\")\n"
"	-- do nothing when initially launching\n"
"end\n"
"function blud.mouse.pressed(x, y, button)\n"
"	print(\"mouse pressed\")\n"
"	-- do nothing when initially launching\n"
"end\n"
"function blud.mouse.released(x, y, button)\n"
"	print(\"mouse released\")\n"
"	-- do nothing when initially launching\n"
"end\n"
"print('blud loaded')\n";